### ISSUE TITLE
Test and document building and flashing of files with Windows

### ISSUE THREAD

**Issue by elenaf9** [Antidott/Softwareprojekt-Telematik#3]

**Comment by nitsuj1001** [comment]
- [ ] Unter Msys2 Make ausführen
- [ ] Kompilieren unter WSL
- [ ] Kompilieren über MingW
- [ ] Kompilieren in VMWare (Ubuntu 22.04)

**Comment by Antidott** [comment]
- [x] build multizone-fpga
- [x] build multizone-sdk
- [x] flash mutlizone-fpga
- [x] flash mutlizone-sdk

**Comment by Antidott** [comment]
> > * [ ]   flash mutlizone-sdk
> 
> Currently blocked, because of an issue with JTAG-connection between my computer and die board. I didn’t managed to fix the issue! We can still already continue with other milestones, and test later.

The same issue occurs on Windows and Arch, because we use Linus-VM on Windows. The issue is extracted into https://github.com/Antidott/Softwareprojekt-Telematik/issues/8.

**Comment by Antidott** [comment]
> * [x]  build multizone-fpga
- Done with [678ccfd](https://github.com/Antidott/Softwareprojekt-Telematik/commit/678ccfd770488997cded5df1c5aea5c73ccaf7f2)

**Comment by Antidott** [comment]
> * [x]  build multizone-sdk
- Done with [e9749b1](https://github.com/Antidott/Softwareprojekt-Telematik/commit/e9749b19d12f2dfcc3f8f422fd35e79069789fd7)

**Comment by Antidott** [comment]
> * [x]  flash mutlizone-sdk

Currently blocked, because of an issue with JTAG-connection between my computer and die board. I didn’t managed to fix the issue! We can still already continue with other milestones, and test later.

**Comment by Antidott** [comment]
> > * [x]   flash mutlizone-sdk
> 
> Currently blocked, because of an issue with JTAG-connection between my computer and die board. I didn’t managed to fix the issue! We can still already continue with other milestones, and test later.

The same issue occurs on Windows and Arch, because we use Linux-VM on Windows. The issue is extracted into https://github.com/Antidott/Softwareprojekt-Telematik/issues/8.

**Comment by elenaf9** [comment]
> > * [x]   build multizone-sdk
> 
>     * Done with

@Antidott I believe this part is still missing in the getting started guide. I am writing the instructions for flashing the firmware right now and wanted to link to it.
